### ISSUE TITLE
Teacher can specify difficulty settings, on main page

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Swearengineers#87]
The idea is that the teacher can specify how many problems they have to get correct in each difficulty category.

For example: 

- 3 easy
- 4 medium
- 2 hard

**Comment by josemvidal** [comment]
Right now, it seems the teacher cannot choose the number of problems that they have to get correct. It is hard-wired to 1 easy, 1 medium, 1 hard.

<img width="939" alt="mathquizzes_" src="https://cloud.githubusercontent.com/assets/228704/25581661/19f6a2c0-2e57-11e7-87a0-e14222cd76d5.png">

**Comment by jeSager** [comment]
### I see...
* The slider values are being stored correctly because they are remembered by the system.  They must not be accessed / used correctly.

* Also, I've been advised that this is an issue that only exists within the teacher-view, and does not exist in the student view.  I have not tested it yet.

* I'm not sure how much effort you'd like me to dedicate to this algorithm, since the client request (s) are so radically different.  I'm going to have to rewrite it. 

<br>

![slider](https://cloud.githubusercontent.com/assets/21075174/25583459/d8f39482-2e5f-11e7-8add-0f8e24104da4.png)

### #66 self-assigned 27 days ago

**Comment by jorypettit** [comment]
Currently it looks like the teacher's version of "test my quiz" and what the student has are a little different. The teacher's version is not dynamic, as we believed the teacher would want to answer all the problems to make sure they were right for the students. After some looking, it appears the student's version is working correctly, however the message they get is misleading. If a student is required to get 2 of each type of problem right, they will receive the "move on" message after one is answered correctly. However, this will not affect the overall grading. If the student correctly answers 2 from each section the grade will be a 100%.
